### ISSUE TITLE
Scroll Repositioning on Orientation Change

### ISSUE THREAD

**Issue by zalo** [chenglou/chenglou.github.io#1]
Hey @chenglou it was nice meeting you yesterday.

Your gallery is awesome!   The uncompromising speed and eye for power-usage easily put this in the top 5% of gallery experiences I've tried!

One behavior that I don't see many 2D -> 1D interfaces try to address is preserving gallery scroll position between landscape and portrait orientation mode.

Do you think your system is flexible enough to handle scroll position preservation?

**Comment by chenglou** [comment]
Hey John! Thank you and nice meeting you too =D

Yeah scroll position preservation is something that I've been thinking about. It's always troublesome due to the browser doing it async and us only being able to read into it after the fact. I'll think of a way of doing it without wrecking things. To be clear, there's nothing this system can't handle since it's just a lightweight, "webby" render loop. But I worry about cleanliness since it's one of the demos I'll show as an example for various purposes, and ~450 lines of code is already exceeding my allotted threshold.

I'll try it this weekend!

**Comment by chenglou** [comment]
Done in https://github.com/chenglou/chenglou.github.io/commit/d6b813705f47a4a4f9dece5522825f38fee9f50d https://github.com/chenglou/chenglou.github.io/commit/d445ac438db7a47f7c67dc45b6c42e3e72b14ad9 https://github.com/chenglou/chenglou.github.io/commit/8b9c25d0438f09403b9e032f13e10d1dfcaa6668 🙂

This is composed of various parts, among which is a suitable anchoring heuristics (made harder by the gallery not always being a 1D scroll), carefully side-stepping browser API shenanigans, controlling complexity which can spill elsewhere (any time scrolling is programmatically modified, the logic becomes more complex due to how browsers work)

https://twitter.com/_chenglou/status/1605798368730497025

This works decently on mobile Safari, with some caveat around image rendering being delayed because it literally throttles them and there's nothing much we can do short of gigantic architecture-changing hacks. I was actually thinking of making a mobile-optimized site though, since this gallery's layout concepts don't even translate to small screens well. Maybe another day!
